/** Indicatifs pour le flux téléphone + OTP (liste courte, extensible). */
export const PHONE_COUNTRY_CODES = [
  { iso: 'fr', name: 'France', code: '+33' },
  { iso: 'be', name: 'Belgique', code: '+32' },
  { iso: 'ch', name: 'Suisse', code: '+41' },
  { iso: 'ca', name: 'Canada', code: '+1' },
  { iso: 'us', name: 'États-Unis', code: '+1' },
  { iso: 'gb', name: 'Royaume-Uni', code: '+44' },
  { iso: 'de', name: 'Allemagne', code: '+49' },
  { iso: 'it', name: 'Italie', code: '+39' },
  { iso: 'es', name: 'Espagne', code: '+34' },
  { iso: 'pt', name: 'Portugal', code: '+351' },
  { iso: 'sn', name: 'Sénégal', code: '+221' },
  { iso: 'ci', name: "Côte d'Ivoire", code: '+225' },
  { iso: 'ml', name: 'Mali', code: '+223' },
  { iso: 'bf', name: 'Burkina Faso', code: '+226' },
  { iso: 'gn', name: 'Guinée', code: '+224' },
  { iso: 'tg', name: 'Togo', code: '+228' },
  { iso: 'bj', name: 'Bénin', code: '+229' },
  { iso: 'cm', name: 'Cameroun', code: '+237' },
  { iso: 'ma', name: 'Maroc', code: '+212' },
  { iso: 'dz', name: 'Algérie', code: '+213' },
  { iso: 'tn', name: 'Tunisie', code: '+216' },
  { iso: 'br', name: 'Brésil', code: '+55' },
] as const;
